In [18]:
import sqlite3

# Create a SQL connection to our SQLite database
con = sqlite3.connect("chinook.db")

cur = con.cursor()

# The result of a "cursor.execute" can be iterated over by row
for row in cur.execute('SELECT * FROM CENSUS_DATA;'):
    print(row)
  

# Be sure to close the connection

con.close()

(1, 'Rogers Park', 7.7, 23.6, 8.7, 18.2, 27.5, 23939, 39)
(2, 'West Ridge', 7.8, 17.2, 8.8, 20.8, 38.5, 23040, 46)
(3, 'Uptown', 3.8, 24.0, 8.9, 11.8, 22.2, 35787, 20)
(4, 'Lincoln Square', 3.4, 10.9, 8.2, 13.4, 25.5, 37524, 17)
(5, 'North Center', 0.3, 7.5, 5.2, 4.5, 26.2, 57123, 6)
(6, 'Lake View', 1.1, 11.4, 4.7, 2.6, 17.0, 60058, 5)
(7, 'Lincoln Park', 0.8, 12.3, 5.1, 3.6, 21.5, 71551, 2)
(8, 'Near North Side', 1.9, 12.9, 7.0, 2.5, 22.6, 88669, 1)
(9, 'Edison Park', 1.1, 3.3, 6.5, 7.4, 35.3, 40959, 8)
(10, 'Norwood Park', 2.0, 5.4, 9.0, 11.5, 39.5, 32875, 21)
(11, 'Jefferson Park', 2.7, 8.6, 12.4, 13.4, 35.5, 27751, 25)
(12, 'Forest Glen', 1.1, 7.5, 6.8, 4.9, 40.5, 44164, 11)
(13, 'North Park', 3.9, 13.2, 9.9, 14.4, 39.0, 26576, 33)
(14, 'Albany Park', 11.3, 19.2, 10.0, 32.9, 32.0, 21323, 53)
(15, 'Portage Park', 4.1, 11.6, 12.6, 19.3, 34.0, 24336, 35)
(16, 'Irving Park', 6.3, 13.1, 10.0, 22.4, 31.6, 27249, 34)
(17, 'Dunning', 5.2, 10.6, 10.0, 16.2, 33.6, 26282, 28)
(18, 'Montclaire', 8.1, 15.3, 13.8, 23.5, 38.6, 22014, 50)
(19, 'Belmont Cragin', 10.8, 18.7, 14.6, 37.3, 37.3, 15461, 70)
(20, 'Hermosa', 6.9, 20.5, 13.1, 41.6, 36.4, 15089, 71)
(21, 'Avondale', 6.0, 15.3, 9.2, 24.7, 31.0, 20039, 42)
(22, 'Logan Square', 3.2, 16.8, 8.2, 14.8, 26.2, 31908, 23)
(23, 'Humboldt park', 14.8, 33.9, 17.3, 35.4, 38.0, 13781, 85)
(24, 'West Town', 2.3, 14.7, 6.6, 12.9, 21.7, 43198, 10)
(25, 'Austin', 6.3, 28.6, 22.6, 24.4, 37.9, 15957, 73)
(26, 'West Garfield Park', 9.4, 41.7, 25.8, 24.5, 43.6, 10934, 92)
(27, 'East Garfield Park', 8.2, 42.4, 19.6, 21.3, 43.2, 12961, 83)
(28, 'Near West Side', 3.8, 20.6, 10.7, 9.6, 22.2, 44689, 15)
(29, 'North Lawndale', 7.4, 43.1, 21.2, 27.6, 42.7, 12034, 87)
(30, 'South Lawndale', 15.2, 30.7, 15.8, 54.8, 33.8, 10402, 96)
(31, 'Lower West Side', 9.6, 25.8, 15.8, 40.7, 32.6, 16444, 76)
(32, 'Loop', 1.5, 14.7, 5.7, 3.1, 13.5, 65526, 3)
(33, 'Near South Side', 1.3, 13.8, 4.9, 7.4, 21.8, 59077, 7)
(34, 'Armour Square', 5.7, 40.1, 16.7, 34.5, 38.3, 16148, 82)
(35, 'Douglas', 1.8, 29.6, 18.2, 14.3, 30.7, 23791, 47)
(36, 'Oakland', 1.3, 39.7, 28.7, 18.4, 40.4, 19252, 78)
(37, 'Fuller Park', 3.2, 51.2, 33.9, 26.6, 44.9, 10432, 97)
(38, 'Grand Boulevard', 3.3, 29.3, 24.3, 15.9, 39.5, 23472, 57)
(39, 'Kenwood', 2.4, 21.7, 15.7, 11.3, 35.4, 35911, 26)
(40, 'Washington Park', 5.6, 42.1, 28.6, 25.4, 42.8, 13785, 88)
(41, 'Hyde Park', 1.5, 18.4, 8.4, 4.3, 26.2, 39056, 14)
(42, 'Woodlawn', 2.9, 30.7, 23.4, 16.5, 36.1, 18672, 58)
(43, 'South Shore', 2.8, 31.1, 20.0, 14.0, 35.7, 19398, 55)
(44, 'Chatham', 3.3, 27.8, 24.0, 14.5, 40.3, 18881, 60)
(45, 'Avalon Park', 1.4, 17.2, 21.1, 10.6, 39.3, 24454, 41)
(46, 'South Chicago', 4.7, 29.8, 19.7, 26.6, 41.1, 16579, 75)
(47, 'Burnside', 6.8, 33.0, 18.6, 19.3, 42.7, 12515, 79)
(48, 'Calumet Heights', 2.1, 11.5, 20.0, 11.0, 44.0, 28887, 38)
(49, 'Roseland', 2.5, 19.8, 20.3, 16.9, 41.2, 17949, 52)
(50, 'Pullman', 1.5, 21.6, 22.8, 13.1, 38.6, 20588, 51)
(51, 'South Deering', 4.0, 29.2, 16.3, 21.0, 39.5, 14685, 65)
(52, 'East Side', 6.8, 19.2, 12.1, 31.9, 42.8, 17104, 64)
(53, 'West Pullman', 3.3, 25.9, 19.4, 20.5, 42.1, 16563, 62)
(54, 'Riverdale', 5.8, 56.5, 34.6, 27.5, 51.5, 8201, 98)
(55, 'Hegewisch', 3.3, 17.1, 9.6, 19.2, 42.9, 22677, 44)
(56, 'Garfield Ridge', 2.6, 8.8, 11.3, 19.3, 38.1, 26353, 32)
(57, 'Archer Heights', 8.5, 14.1, 16.5, 35.9, 39.2, 16134, 67)
(58, 'Brighton Park', 14.4, 23.6, 13.9, 45.1, 39.3, 13089, 84)
(59, 'McKinley Park', 7.2, 18.7, 13.4, 32.9, 35.6, 16954, 61)
(60, 'Bridgeport', 4.5, 18.9, 13.7, 22.2, 31.3, 22694, 43)
(61, 'New City', 11.9, 29.0, 23.0, 41.5, 38.9, 12765, 91)
(62, 'West Elsdon', 11.1, 15.6, 16.7, 37.0, 37.7, 15754, 69)
(63, 'Gage Park', 15.8, 23.4, 18.2, 51.5, 38.8, 12171, 93)
(64, 'Clearing', 2.7, 8.9, 9.5, 18.8, 37.6, 25113, 29)
(65, 'West Lawn', 5.8, 14.9, 9.6, 33.6, 39.6, 16907, 56)
(66, 'Chicago Lawn', 7.6, 27.9, 17.1, 31.2, 40.6, 13231, 80)
(67, 'West Englewood', 4.8, 34.4, 35.9, 26.3, 40.7, 11317, 89)
(68, 'Englewood', 3.8, 46.6, 28.0, 28.5, 42.5, 11888, 94)
(69, 'Greater Grand Crossing', 3.6, 29.6, 23.0, 16.5, 41.0, 17285, 66)
(70, 'Ashburn', 4.0, 10.4, 11.7, 17.7, 36.9, 23482, 37)
(71, 'Auburn Gresham', 4.0, 27.6, 28.3, 18.5, 41.9, 15528, 74)
(72, 'Beverly', 0.9, 5.1, 8.0, 3.7, 40.5, 39523, 12)
(73, 'Washington Height', 1.1, 16.9, 20.8, 13.7, 42.6, 19713, 48)
(74, 'Mount Greenwood', 1.0, 3.4, 8.7, 4.3, 36.8, 34381, 16)
(75, 'Morgan Park', 0.8, 13.2, 15.0, 10.8, 40.3, 27149, 30)
(76, "O'Hare", 3.6, 15.4, 7.1, 10.9, 30.3, 25828, 24)
(77, 'Edgewater', 4.1, 18.2, 9.2, 9.7, 23.8, 33385, 19)
(None, 'CHICAGO', 4.7, 19.7, 12.9, 19.5, 33.5, 28202, None)

In [19]:
!pip install ipython-sql

Requirement already satisfied: ipython-sql in c:\users\cheta\anaconda3\lib\site-packages (0.5.0)
Requirement already satisfied: ipython in c:\users\cheta\anaconda3\lib\site-packages (from ipython-sql) (7.31.1)
Requirement already satisfied: six in c:\users\cheta\anaconda3\lib\site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: prettytable in c:\users\cheta\anaconda3\lib\site-packages (from ipython-sql) (3.9.0)
Requirement already satisfied: ipython-genutils in c:\users\cheta\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: sqlparse in c:\users\cheta\anaconda3\lib\site-packages (from ipython-sql) (0.4.4)
Requirement already satisfied: sqlalchemy>=2.0 in c:\users\cheta\anaconda3\lib\site-packages (from ipython-sql) (2.0.22)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\cheta\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (1.1.1)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\cheta\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.3.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\cheta\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.20)
Requirement already satisfied: decorator in c:\users\cheta\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\cheta\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.18.1)
Requirement already satisfied: pickleshare in c:\users\cheta\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in c:\users\cheta\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: backcall in c:\users\cheta\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: colorama in c:\users\cheta\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.5)
Requirement already satisfied: pygments in c:\users\cheta\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.11.2)
Requirement already satisfied: matplotlib-inline in c:\users\cheta\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: setuptools>=18.5 in c:\users\cheta\anaconda3\lib\site-packages (from ipython->ipython-sql) (63.4.1)
Requirement already satisfied: wcwidth in c:\users\cheta\anaconda3\lib\site-packages (from prettytable->ipython-sql) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\cheta\anaconda3\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)

In [20]:
!pip install -q pandas==1.1.5

In [21]:
import sqlite3

# Create a SQL connection to our SQLite database
con = sqlite3.connect("chinook.db")

cur = con.cursor()

# The result of a "cursor.execute" can be iterated over by row
for row in cur.execute('SELECT * FROM CENSUS_DATA;'):
    print(row)
  

# Be sure to close the connection
con.close()

(1, 'Rogers Park', 7.7, 23.6, 8.7, 18.2, 27.5, 23939, 39)
(2, 'West Ridge', 7.8, 17.2, 8.8, 20.8, 38.5, 23040, 46)
(3, 'Uptown', 3.8, 24.0, 8.9, 11.8, 22.2, 35787, 20)
(4, 'Lincoln Square', 3.4, 10.9, 8.2, 13.4, 25.5, 37524, 17)
(5, 'North Center', 0.3, 7.5, 5.2, 4.5, 26.2, 57123, 6)
(6, 'Lake View', 1.1, 11.4, 4.7, 2.6, 17.0, 60058, 5)
(7, 'Lincoln Park', 0.8, 12.3, 5.1, 3.6, 21.5, 71551, 2)
(8, 'Near North Side', 1.9, 12.9, 7.0, 2.5, 22.6, 88669, 1)
(9, 'Edison Park', 1.1, 3.3, 6.5, 7.4, 35.3, 40959, 8)
(10, 'Norwood Park', 2.0, 5.4, 9.0, 11.5, 39.5, 32875, 21)
(11, 'Jefferson Park', 2.7, 8.6, 12.4, 13.4, 35.5, 27751, 25)
(12, 'Forest Glen', 1.1, 7.5, 6.8, 4.9, 40.5, 44164, 11)
(13, 'North Park', 3.9, 13.2, 9.9, 14.4, 39.0, 26576, 33)
(14, 'Albany Park', 11.3, 19.2, 10.0, 32.9, 32.0, 21323, 53)
(15, 'Portage Park', 4.1, 11.6, 12.6, 19.3, 34.0, 24336, 35)
(16, 'Irving Park', 6.3, 13.1, 10.0, 22.4, 31.6, 27249, 34)
(17, 'Dunning', 5.2, 10.6, 10.0, 16.2, 33.6, 26282, 28)
(18, 'Montclaire', 8.1, 15.3, 13.8, 23.5, 38.6, 22014, 50)
(19, 'Belmont Cragin', 10.8, 18.7, 14.6, 37.3, 37.3, 15461, 70)
(20, 'Hermosa', 6.9, 20.5, 13.1, 41.6, 36.4, 15089, 71)
(21, 'Avondale', 6.0, 15.3, 9.2, 24.7, 31.0, 20039, 42)
(22, 'Logan Square', 3.2, 16.8, 8.2, 14.8, 26.2, 31908, 23)
(23, 'Humboldt park', 14.8, 33.9, 17.3, 35.4, 38.0, 13781, 85)
(24, 'West Town', 2.3, 14.7, 6.6, 12.9, 21.7, 43198, 10)
(25, 'Austin', 6.3, 28.6, 22.6, 24.4, 37.9, 15957, 73)
(26, 'West Garfield Park', 9.4, 41.7, 25.8, 24.5, 43.6, 10934, 92)
(27, 'East Garfield Park', 8.2, 42.4, 19.6, 21.3, 43.2, 12961, 83)
(28, 'Near West Side', 3.8, 20.6, 10.7, 9.6, 22.2, 44689, 15)
(29, 'North Lawndale', 7.4, 43.1, 21.2, 27.6, 42.7, 12034, 87)
(30, 'South Lawndale', 15.2, 30.7, 15.8, 54.8, 33.8, 10402, 96)
(31, 'Lower West Side', 9.6, 25.8, 15.8, 40.7, 32.6, 16444, 76)
(32, 'Loop', 1.5, 14.7, 5.7, 3.1, 13.5, 65526, 3)
(33, 'Near South Side', 1.3, 13.8, 4.9, 7.4, 21.8, 59077, 7)
(34, 'Armour Square', 5.7, 40.1, 16.7, 34.5, 38.3, 16148, 82)
(35, 'Douglas', 1.8, 29.6, 18.2, 14.3, 30.7, 23791, 47)
(36, 'Oakland', 1.3, 39.7, 28.7, 18.4, 40.4, 19252, 78)
(37, 'Fuller Park', 3.2, 51.2, 33.9, 26.6, 44.9, 10432, 97)
(38, 'Grand Boulevard', 3.3, 29.3, 24.3, 15.9, 39.5, 23472, 57)
(39, 'Kenwood', 2.4, 21.7, 15.7, 11.3, 35.4, 35911, 26)
(40, 'Washington Park', 5.6, 42.1, 28.6, 25.4, 42.8, 13785, 88)
(41, 'Hyde Park', 1.5, 18.4, 8.4, 4.3, 26.2, 39056, 14)
(42, 'Woodlawn', 2.9, 30.7, 23.4, 16.5, 36.1, 18672, 58)
(43, 'South Shore', 2.8, 31.1, 20.0, 14.0, 35.7, 19398, 55)
(44, 'Chatham', 3.3, 27.8, 24.0, 14.5, 40.3, 18881, 60)
(45, 'Avalon Park', 1.4, 17.2, 21.1, 10.6, 39.3, 24454, 41)
(46, 'South Chicago', 4.7, 29.8, 19.7, 26.6, 41.1, 16579, 75)
(47, 'Burnside', 6.8, 33.0, 18.6, 19.3, 42.7, 12515, 79)
(48, 'Calumet Heights', 2.1, 11.5, 20.0, 11.0, 44.0, 28887, 38)
(49, 'Roseland', 2.5, 19.8, 20.3, 16.9, 41.2, 17949, 52)
(50, 'Pullman', 1.5, 21.6, 22.8, 13.1, 38.6, 20588, 51)
(51, 'South Deering', 4.0, 29.2, 16.3, 21.0, 39.5, 14685, 65)
(52, 'East Side', 6.8, 19.2, 12.1, 31.9, 42.8, 17104, 64)
(53, 'West Pullman', 3.3, 25.9, 19.4, 20.5, 42.1, 16563, 62)
(54, 'Riverdale', 5.8, 56.5, 34.6, 27.5, 51.5, 8201, 98)
(55, 'Hegewisch', 3.3, 17.1, 9.6, 19.2, 42.9, 22677, 44)
(56, 'Garfield Ridge', 2.6, 8.8, 11.3, 19.3, 38.1, 26353, 32)
(57, 'Archer Heights', 8.5, 14.1, 16.5, 35.9, 39.2, 16134, 67)
(58, 'Brighton Park', 14.4, 23.6, 13.9, 45.1, 39.3, 13089, 84)
(59, 'McKinley Park', 7.2, 18.7, 13.4, 32.9, 35.6, 16954, 61)
(60, 'Bridgeport', 4.5, 18.9, 13.7, 22.2, 31.3, 22694, 43)
(61, 'New City', 11.9, 29.0, 23.0, 41.5, 38.9, 12765, 91)
(62, 'West Elsdon', 11.1, 15.6, 16.7, 37.0, 37.7, 15754, 69)
(63, 'Gage Park', 15.8, 23.4, 18.2, 51.5, 38.8, 12171, 93)
(64, 'Clearing', 2.7, 8.9, 9.5, 18.8, 37.6, 25113, 29)
(65, 'West Lawn', 5.8, 14.9, 9.6, 33.6, 39.6, 16907, 56)
(66, 'Chicago Lawn', 7.6, 27.9, 17.1, 31.2, 40.6, 13231, 80)
(67, 'West Englewood', 4.8, 34.4, 35.9, 26.3, 40.7, 11317, 89)
(68, 'Englewood', 3.8, 46.6, 28.0, 28.5, 42.5, 11888, 94)
(69, 'Greater Grand Crossing', 3.6, 29.6, 23.0, 16.5, 41.0, 17285, 66)
(70, 'Ashburn', 4.0, 10.4, 11.7, 17.7, 36.9, 23482, 37)
(71, 'Auburn Gresham', 4.0, 27.6, 28.3, 18.5, 41.9, 15528, 74)
(72, 'Beverly', 0.9, 5.1, 8.0, 3.7, 40.5, 39523, 12)
(73, 'Washington Height', 1.1, 16.9, 20.8, 13.7, 42.6, 19713, 48)
(74, 'Mount Greenwood', 1.0, 3.4, 8.7, 4.3, 36.8, 34381, 16)
(75, 'Morgan Park', 0.8, 13.2, 15.0, 10.8, 40.3, 27149, 30)
(76, "O'Hare", 3.6, 15.4, 7.1, 10.9, 30.3, 25828, 24)
(77, 'Edgewater', 4.1, 18.2, 9.2, 9.7, 23.8, 33385, 19)
(None, 'CHICAGO', 4.7, 19.7, 12.9, 19.5, 33.5, 28202, None)

In [22]:
con = sqlite3.connect("chinook.db")
cur = con.cursor()
cur.execute('''
          INSERT INTO Census_Data (COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME )
          VALUES
                (78, 'Lakeshore')               
          ''')

for row in cur.execute('SELECT * FROM Census_Data;'):
    print(row)

# Be sure to close the connection
con.close()

(1, 'Rogers Park', 7.7, 23.6, 8.7, 18.2, 27.5, 23939, 39)
(2, 'West Ridge', 7.8, 17.2, 8.8, 20.8, 38.5, 23040, 46)
(3, 'Uptown', 3.8, 24.0, 8.9, 11.8, 22.2, 35787, 20)
(4, 'Lincoln Square', 3.4, 10.9, 8.2, 13.4, 25.5, 37524, 17)
(5, 'North Center', 0.3, 7.5, 5.2, 4.5, 26.2, 57123, 6)
(6, 'Lake View', 1.1, 11.4, 4.7, 2.6, 17.0, 60058, 5)
(7, 'Lincoln Park', 0.8, 12.3, 5.1, 3.6, 21.5, 71551, 2)
(8, 'Near North Side', 1.9, 12.9, 7.0, 2.5, 22.6, 88669, 1)
(9, 'Edison Park', 1.1, 3.3, 6.5, 7.4, 35.3, 40959, 8)
(10, 'Norwood Park', 2.0, 5.4, 9.0, 11.5, 39.5, 32875, 21)
(11, 'Jefferson Park', 2.7, 8.6, 12.4, 13.4, 35.5, 27751, 25)
(12, 'Forest Glen', 1.1, 7.5, 6.8, 4.9, 40.5, 44164, 11)
(13, 'North Park', 3.9, 13.2, 9.9, 14.4, 39.0, 26576, 33)
(14, 'Albany Park', 11.3, 19.2, 10.0, 32.9, 32.0, 21323, 53)
(15, 'Portage Park', 4.1, 11.6, 12.6, 19.3, 34.0, 24336, 35)
(16, 'Irving Park', 6.3, 13.1, 10.0, 22.4, 31.6, 27249, 34)
(17, 'Dunning', 5.2, 10.6, 10.0, 16.2, 33.6, 26282, 28)
(18, 'Montclaire', 8.1, 15.3, 13.8, 23.5, 38.6, 22014, 50)
(19, 'Belmont Cragin', 10.8, 18.7, 14.6, 37.3, 37.3, 15461, 70)
(20, 'Hermosa', 6.9, 20.5, 13.1, 41.6, 36.4, 15089, 71)
(21, 'Avondale', 6.0, 15.3, 9.2, 24.7, 31.0, 20039, 42)
(22, 'Logan Square', 3.2, 16.8, 8.2, 14.8, 26.2, 31908, 23)
(23, 'Humboldt park', 14.8, 33.9, 17.3, 35.4, 38.0, 13781, 85)
(24, 'West Town', 2.3, 14.7, 6.6, 12.9, 21.7, 43198, 10)
(25, 'Austin', 6.3, 28.6, 22.6, 24.4, 37.9, 15957, 73)
(26, 'West Garfield Park', 9.4, 41.7, 25.8, 24.5, 43.6, 10934, 92)
(27, 'East Garfield Park', 8.2, 42.4, 19.6, 21.3, 43.2, 12961, 83)
(28, 'Near West Side', 3.8, 20.6, 10.7, 9.6, 22.2, 44689, 15)
(29, 'North Lawndale', 7.4, 43.1, 21.2, 27.6, 42.7, 12034, 87)
(30, 'South Lawndale', 15.2, 30.7, 15.8, 54.8, 33.8, 10402, 96)
(31, 'Lower West Side', 9.6, 25.8, 15.8, 40.7, 32.6, 16444, 76)
(32, 'Loop', 1.5, 14.7, 5.7, 3.1, 13.5, 65526, 3)
(33, 'Near South Side', 1.3, 13.8, 4.9, 7.4, 21.8, 59077, 7)
(34, 'Armour Square', 5.7, 40.1, 16.7, 34.5, 38.3, 16148, 82)
(35, 'Douglas', 1.8, 29.6, 18.2, 14.3, 30.7, 23791, 47)
(36, 'Oakland', 1.3, 39.7, 28.7, 18.4, 40.4, 19252, 78)
(37, 'Fuller Park', 3.2, 51.2, 33.9, 26.6, 44.9, 10432, 97)
(38, 'Grand Boulevard', 3.3, 29.3, 24.3, 15.9, 39.5, 23472, 57)
(39, 'Kenwood', 2.4, 21.7, 15.7, 11.3, 35.4, 35911, 26)
(40, 'Washington Park', 5.6, 42.1, 28.6, 25.4, 42.8, 13785, 88)
(41, 'Hyde Park', 1.5, 18.4, 8.4, 4.3, 26.2, 39056, 14)
(42, 'Woodlawn', 2.9, 30.7, 23.4, 16.5, 36.1, 18672, 58)
(43, 'South Shore', 2.8, 31.1, 20.0, 14.0, 35.7, 19398, 55)
(44, 'Chatham', 3.3, 27.8, 24.0, 14.5, 40.3, 18881, 60)
(45, 'Avalon Park', 1.4, 17.2, 21.1, 10.6, 39.3, 24454, 41)
(46, 'South Chicago', 4.7, 29.8, 19.7, 26.6, 41.1, 16579, 75)
(47, 'Burnside', 6.8, 33.0, 18.6, 19.3, 42.7, 12515, 79)
(48, 'Calumet Heights', 2.1, 11.5, 20.0, 11.0, 44.0, 28887, 38)
(49, 'Roseland', 2.5, 19.8, 20.3, 16.9, 41.2, 17949, 52)
(50, 'Pullman', 1.5, 21.6, 22.8, 13.1, 38.6, 20588, 51)
(51, 'South Deering', 4.0, 29.2, 16.3, 21.0, 39.5, 14685, 65)
(52, 'East Side', 6.8, 19.2, 12.1, 31.9, 42.8, 17104, 64)
(53, 'West Pullman', 3.3, 25.9, 19.4, 20.5, 42.1, 16563, 62)
(54, 'Riverdale', 5.8, 56.5, 34.6, 27.5, 51.5, 8201, 98)
(55, 'Hegewisch', 3.3, 17.1, 9.6, 19.2, 42.9, 22677, 44)
(56, 'Garfield Ridge', 2.6, 8.8, 11.3, 19.3, 38.1, 26353, 32)
(57, 'Archer Heights', 8.5, 14.1, 16.5, 35.9, 39.2, 16134, 67)
(58, 'Brighton Park', 14.4, 23.6, 13.9, 45.1, 39.3, 13089, 84)
(59, 'McKinley Park', 7.2, 18.7, 13.4, 32.9, 35.6, 16954, 61)
(60, 'Bridgeport', 4.5, 18.9, 13.7, 22.2, 31.3, 22694, 43)
(61, 'New City', 11.9, 29.0, 23.0, 41.5, 38.9, 12765, 91)
(62, 'West Elsdon', 11.1, 15.6, 16.7, 37.0, 37.7, 15754, 69)
(63, 'Gage Park', 15.8, 23.4, 18.2, 51.5, 38.8, 12171, 93)
(64, 'Clearing', 2.7, 8.9, 9.5, 18.8, 37.6, 25113, 29)
(65, 'West Lawn', 5.8, 14.9, 9.6, 33.6, 39.6, 16907, 56)
(66, 'Chicago Lawn', 7.6, 27.9, 17.1, 31.2, 40.6, 13231, 80)
(67, 'West Englewood', 4.8, 34.4, 35.9, 26.3, 40.7, 11317, 89)
(68, 'Englewood', 3.8, 46.6, 28.0, 28.5, 42.5, 11888, 94)
(69, 'Greater Grand Crossing', 3.6, 29.6, 23.0, 16.5, 41.0, 17285, 66)
(70, 'Ashburn', 4.0, 10.4, 11.7, 17.7, 36.9, 23482, 37)
(71, 'Auburn Gresham', 4.0, 27.6, 28.3, 18.5, 41.9, 15528, 74)
(72, 'Beverly', 0.9, 5.1, 8.0, 3.7, 40.5, 39523, 12)
(73, 'Washington Height', 1.1, 16.9, 20.8, 13.7, 42.6, 19713, 48)
(74, 'Mount Greenwood', 1.0, 3.4, 8.7, 4.3, 36.8, 34381, 16)
(75, 'Morgan Park', 0.8, 13.2, 15.0, 10.8, 40.3, 27149, 30)
(76, "O'Hare", 3.6, 15.4, 7.1, 10.9, 30.3, 25828, 24)
(77, 'Edgewater', 4.1, 18.2, 9.2, 9.7, 23.8, 33385, 19)
(None, 'CHICAGO', 4.7, 19.7, 12.9, 19.5, 33.5, 28202, None)
(78, 'Lakeshore', None, None, None, None, None, None, None)

In [33]:
!pip install sqlalchemy==1.3.9
!pip install ibm_db_sa
!pip install ipython-sql
%load_ext sql
%sql sqlite:///chinook.db

Collecting sqlalchemy==1.3.9
  Using cached SQLAlchemy-1.3.9-cp39-cp39-win_amd64.whl
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.22
    Uninstalling SQLAlchemy-2.0.22:
      Successfully uninstalled SQLAlchemy-2.0.22
Successfully installed sqlalchemy-1.3.9

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython-sql 0.5.0 requires sqlalchemy>=2.0, but you have sqlalchemy 1.3.9 which is incompatible.

Requirement already satisfied: ibm_db_sa in c:\users\cheta\anaconda3\lib\site-packages (0.4.0)
Requirement already satisfied: sqlalchemy>=0.7.3 in c:\users\cheta\anaconda3\lib\site-packages (from ibm_db_sa) (1.3.9)
Requirement already satisfied: ibm-db>=2.0.0 in c:\users\cheta\anaconda3\lib\site-packages (from ibm_db_sa) (3.2.0)
Requirement already satisfied: ipython-sql in c:\users\cheta\anaconda3\lib\site-packages (0.5.0)
Requirement already satisfied: sqlparse in c:\users\cheta\anaconda3\lib\site-packages (from ipython-sql) (0.4.4)
Requirement already satisfied: ipython-genutils in c:\users\cheta\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: ipython in c:\users\cheta\anaconda3\lib\site-packages (from ipython-sql) (7.31.1)
Requirement already satisfied: prettytable in c:\users\cheta\anaconda3\lib\site-packages (from ipython-sql) (3.9.0)
Collecting sqlalchemy>=2.0
  Using cached SQLAlchemy-2.0.22-cp39-cp39-win_amd64.whl (2.1 MB)
Requirement already satisfied: six in c:\users\cheta\anaconda3\lib\site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\cheta\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.3.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\cheta\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (1.1.1)
Requirement already satisfied: pickleshare in c:\users\cheta\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.7.5)
Requirement already satisfied: matplotlib-inline in c:\users\cheta\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: decorator in c:\users\cheta\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: setuptools>=18.5 in c:\users\cheta\anaconda3\lib\site-packages (from ipython->ipython-sql) (63.4.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\cheta\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.20)
Requirement already satisfied: colorama in c:\users\cheta\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.5)
Requirement already satisfied: jedi>=0.16 in c:\users\cheta\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.18.1)
Requirement already satisfied: pygments in c:\users\cheta\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.11.2)
Requirement already satisfied: traitlets>=4.2 in c:\users\cheta\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: backcall in c:\users\cheta\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: wcwidth in c:\users\cheta\anaconda3\lib\site-packages (from prettytable->ipython-sql) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\cheta\anaconda3\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 1.3.9
    Uninstalling SQLAlchemy-1.3.9:
      Successfully uninstalled SQLAlchemy-1.3.9
Successfully installed sqlalchemy-2.0.22
The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [34]:
%%sql
SELECT
    name
FROM
    sqlite_master
WHERE
    type='table'

 * sqlite:///chinook.db
Done.

[('CHICAGO_CRIME_DATA',),
 ('CHICAGO_PUBLIC_SCHOOLS',),
 ('CENSUS_DATA',),
 ('Movies',),
 ('Fam',)]

In [32]:
%sql select * from movies

 * sqlite:///chinook.db
Done.

[(901, 'Vertigo', 1958, 128, 'English', '1958-08-24', 'UK', 'Righty Sock', 9001, '8.4', '263575'),
 (902, 'The Innocents', 1961, 100, 'English', '1962-02-19', 'SW', 'Jack Malvern', 9002, '7.9', '20207'),
 (903, 'Lawrence of Arabia', 1962, 216, 'English', '1962-12-11', 'UK', 'Flagrant Baronessa', 9003, '8.3', '202778'),
 (904, 'The Deer Hunter', 1978, 183, 'English', '1979-03-08', 'UK', 'Alec Shaw', 9005, '8.2', '484746'),
 (905, 'Amadeus', 1984, 160, 'English', '1985-01-07', 'UK', 'Francois Truffaut', 9006, '7.3', None),
 (906, 'Blade Runner', 1982, 117, 'English', '1982-09-09', 'UK', 'Victor Woeltjen', 9007, '8.6', '779489'),
 (907, 'Eyes Wide Shut', 1999, 159, 'English', None, 'UK', 'Simon Wright', 9008, None, '227235'),
 (908, 'The Usual Suspects', 1995, 106, 'English', '1995-08-25', 'UK', 'Neal Wruck', 9009, '3', '195961'),
 (909, 'Chinatown', 1974, 130, 'English', '1974-08-09', 'UK', 'Paul Monks', 9010, '8.1', '203875'),
 (910, 'Boogie Nights', 1997, 155, 'English', '1998-02-16', 'UK', 'Mike Salvati', 9011, '8.4', None),
 (911, 'Annie Hall', 1977, 93, 'English', '1977-04-20', 'USA', 'Armond White', 9013, '7', '862618'),
 (912, 'Princess Mononoke', 1997, 134, 'Japanese', '2001-10-19', 'UK', 'Wesley S. Walker', 9001, '7.7', '830095'),
 (913, 'The Shawshank Redemption', 1994, 142, 'English', '1995-02-17', 'UK', 'Sasha Goldshtein', 9014, '4', '642132'),
 (914, 'American Beauty', 1999, 122, 'English', None, 'UK', 'Josh Cates', 9015, '7.7', '81328'),
 (915, 'Titanic', 1997, 194, 'English', '1998-01-23', 'UK', 'Krug Stillo', 9016, None, '580301'),
 (916, 'Good Will Hunting', 1997, 126, 'English', '1998-06-03', 'UK', 'Scott LeBrun', 9017, '8.1', '609451'),
 (917, 'Deliverance', 1972, 109, 'English', '1982-10-05', 'UK', 'Hannah Steele', 9018, '8', '667758'),
 (918, 'Trainspotting', 1996, 94, 'English', '1996-02-23', 'UK', 'Vincent Cadena', 9019, '8.4', '511613'),
 (919, 'The Prestige', 2006, 130, 'English', '2006-11-10', 'UK', 'Brandt Sponseller', 9020, '6.7', '13091'),
 (920, 'Donnie Darko', 2001, 113, 'English', None, 'UK', 'Richard Adams', 9021, '7', '544452'),
 (921, 'Slumdog Millionaire', 2008, 120, 'English', '2009-01-09', 'UK', 'Andre Bazin', 9022, '7', '557054'),
 (922, 'Aliens', 1986, 137, 'English', '1986-08-29', 'UK', 'Judith Christ', 9023, '7', '569657'),
 (923, 'Beyond the Sea', 2004, 118, 'English', '2004-11-26', 'UK', 'Peter Travers', 9024, '6.9', '582260'),
 (924, 'Avatar', 2009, 162, 'English', '2009-12-17', 'UK', 'Roger Ebert', 9025, '6.9', '594862'),
 (926, 'Seven Samurai', 1954, 207, 'Japanese', '1954-04-26', 'JP', 'Pauline Kael', 9026, '6.9', '607465'),
 (927, 'Spirited Away', 2001, 125, 'Japanese', '2003-09-12', 'UK', 'Leonard Martin', 9027, '6.8', '620067'),
 (928, 'Back to the Future', 1985, 116, 'English', '1985-12-04', 'UK', 'Andrew Sarris', 9028, '6.8', '632670'),
 (925, 'Braveheart', 1995, 178, 'English', '1995-09-08', 'UK', 'Gene Shalit', 9029, '6.8', '645273')]

In [26]:
%%sql

CREATE TABLE Fam(Name TEXT, Age INTEGER, Profession TEXT, Major TEXT);
INSERT INTO Fam (Name, Age) VALUES('Pam', 50);
INSERT INTO Fam (Name, Age) VALUES('Miranda', 32);
INSERT INTO Fam (Name, Age) VALUES('Pascal', 45);
INSERT INTO Fam (Name, Age) VALUES('Dave', 12);
INSERT INTO Fam (Name, Age) VALUES('Emmy', 23);

UPDATE Fam SET Profession='Unknown' WHERE Profession ISNULL

 * sqlite:///chinook.db
(sqlite3.OperationalError) table Fam already exists
[SQL: CREATE TABLE Fam(Name TEXT, Age INTEGER, Profession TEXT, Major TEXT);]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [27]:
%%sql
SELECT
    name
FROM
    sqlite_master
WHERE
    type='table'

 * sqlite:///chinook.db
Done.

[('CHICAGO_CRIME_DATA',),
 ('CHICAGO_PUBLIC_SCHOOLS',),
 ('CENSUS_DATA',),
 ('Movies',),
 ('Fam',)]

In [28]:
import pandas as pd
result = %sql select * from movies
dataframe = result.DataFrame()
dataframe

 * sqlite:///chinook.db
Done.

,mov_id,mov_name,mov_year,mov_time,mov_lang,mov_dt_rel,mov_rel_country,rev_name,rev_id,rev_stars,num_o_ratings
0,901,Vertigo,1958,128,English,1958-08-24,UK,Righty Sock,9001,8.4,263575
1,902,The Innocents,1961,100,English,1962-02-19,SW,Jack Malvern,9002,7.9,20207
2,903,Lawrence of Arabia,1962,216,English,1962-12-11,UK,Flagrant Baronessa,9003,8.3,202778
3,904,The Deer Hunter,1978,183,English,1979-03-08,UK,Alec Shaw,9005,8.2,484746
4,905,Amadeus,1984,160,English,1985-01-07,UK,Francois Truffaut,9006,7.3,None
5,906,Blade Runner,1982,117,English,1982-09-09,UK,Victor Woeltjen,9007,8.6,779489
6,907,Eyes Wide Shut,1999,159,English,None,UK,Simon Wright,9008,None,227235
7,908,The Usual Suspects,1995,106,English,1995-08-25,UK,Neal Wruck,9009,3,195961
8,909,Chinatown,1974,130,English,1974-08-09,UK,Paul Monks,9010,8.1,203875
9,910,Boogie Nights,1997,155,English,1998-02-16,UK,Mike Salvati,9011,8.4,None
10,911,Annie Hall,1977,93,English,1977-04-20,USA,Armond White,9013,7,862618
11,912,Princess Mononoke,1997,134,Japanese,2001-10-19,UK,Wesley S. Walker,9001,7.7,830095
12,913,The Shawshank Redemption,1994,142,English,1995-02-17,UK,Sasha Goldshtein,9014,4,642132
13,914,American Beauty,1999,122,English,None,UK,Josh Cates,9015,7.7,81328
14,915,Titanic,1997,194,English,1998-01-23,UK,Krug Stillo,9016,None,580301
15,916,Good Will Hunting,1997,126,English,1998-06-03,UK,Scott LeBrun,9017,8.1,609451
16,917,Deliverance,1972,109,English,1982-10-05,UK,Hannah Steele,9018,8,667758
17,918,Trainspotting,1996,94,English,1996-02-23,UK,Vincent Cadena,9019,8.4,511613
18,919,The Prestige,2006,130,English,2006-11-10,UK,Brandt Sponseller,9020,6.7,13091
19,920,Donnie Darko,2001,113,English,None,UK,Richard Adams,9021,7,544452
20,921,Slumdog Millionaire,2008,120,English,2009-01-09,UK,Andre Bazin,9022,7,557054
21,922,Aliens,1986,137,English,1986-08-29,UK,Judith Christ,9023,7,569657
22,923,Beyond the Sea,2004,118,English,2004-11-26,UK,Peter Travers,9024,6.9,582260
23,924,Avatar,2009,162,English,2009-12-17,UK,Roger Ebert,9025,6.9,594862
24,926,Seven Samurai,1954,207,Japanese,1954-04-26,JP,Pauline Kael,9026,6.9,607465
25,927,Spirited Away,2001,125,Japanese,2003-09-12,UK,Leonard Martin,9027,6.8,620067
26,928,Back to the Future,1985,116,English,1985-12-04,UK,Andrew Sarris,9028,6.8,632670
27,925,Braveheart,1995,178,English,1995-09-08,UK,Gene Shalit,9029,6.8,645273

# 1. Find the total number of crimes recorded in the CRIME table.

In [37]:
%%sql

SELECT COUNT(*) as total_crimes
FROM CHICAGO_CRIME_DATA;

 * sqlite:///chinook.db
Done.

[(533,)]

# 2. List community areas with per capita income less than 11000.

In [38]:
%%sql
SELECT COMMUNITY_AREA_NAME, PER_CAPITA_INCOME 
FROM CENSUS_DATA
WHERE PER_CAPITA_INCOME < 11000;

 * sqlite:///chinook.db
Done.

[('West Garfield Park', 10934),
 ('South Lawndale', 10402),
 ('Fuller Park', 10432),
 ('Riverdale', 8201)]

# 3. List all case numbers for crimes involving minors?(children are not considered minors for the purposes of crime analysis)

In [66]:
%%sql

SELECT CASE_NUMBER
FROM CHICAGO_CRIME_DATA
WHERE PRIMARY_TYPE = 'OFFENSE INVOLVING CHILDREN'

 * sqlite:///chinook.db
Done.

[('HN567387',), ('HR391350',), ('HM768251',), ('HT394616',)]

# 4. List all kidnapping crimes involving a child?¶

In [85]:
%%sql

SELECT DISTINCT PRIMARY_TYPE
FROM CHICAGO_CRIME_DATA
WHERE PRIMARY_TYPE = 'KIDNAPPING' AND DESCRIPTION LIKE '%CHILD%'

 * sqlite:///chinook.db
Done.

[('KIDNAPPING',)]

# 5. What kinds of crimes were recorded at schools?

In [71]:
%%sql

SELECT DISTINCT PRIMARY_TYPE
FROM CHICAGO_CRIME_DATA
WHERE Location_DESCRIPTION LIKE '%School%'

 * sqlite:///chinook.db
Done.

[('BATTERY',),
 ('CRIMINAL DAMAGE',),
 ('NARCOTICS',),
 ('ASSAULT',),
 ('CRIMINAL TRESPASS',),
 ('PUBLIC PEACE VIOLATION',)]

# 6. List the average safety score for each type of school.

In [54]:
%%sql

SELECT NAME_OF_SCHOOL, AVG(SAFETY_SCORE) AS AVERAGE_SAFETY_SCORE
FROM CHICAGO_PUBLIC_SCHOOLS
GROUP BY NAME_OF_SCHOOL;

 * sqlite:///chinook.db
Done.

[('A.N. Pritzker School', 59.0),
 ('Abraham Lincoln Elementary School', 99.0),
 ('Adam Clayton Powell Paideia Community Academy Elementary School', 54.0),
 ('Adlai E Stevenson Elementary School', 61.0),
 ('Agustin Lara Elementary Academy', 56.0),
 ('Air Force Academy High School', 49.0),
 ('Al Raby High School', 52.0),
 ('Albany Park Multicultural Academy', 66.0),
 ('Albert G Lane Technical High School', 88.0),
 ('Albert R Sabin Elementary Magnet School', 67.0),
 ('Alcott High School for the Humanities', 70.0),
 ('Alessandro Volta Elementary School', 43.0),
 ('Alex Haley Elementary Academy', 28.0),
 ('Alexander Graham Bell Elementary School', 99.0),
 ('Alexander Graham Elementary School', 49.0),
 ('Alexander Hamilton Elementary School', 73.0),
 ('Alexander von Humboldt Elementary School', 31.0),
 ('Alfred David Kohn Elementary School', 19.0),
 ('Alfred Nobel Elementary School', 37.0),
 ('Alice L Barnard Computer Math & Science Center Elementary School', 46.0),
 ('Ambrose Plamondon Elementary School', 45.0),
 ('Amelia Earhart Options for Knowledge Elementary School', 81.0),
 ('Ames Middle School', 38.0),
 ('Amos Alonzo Stagg Elementary School', 23.0),
 ('Ana Roque de Duprey Elementary School', 57.0),
 ('Andrew Carnegie Elementary School', 48.0),
 ('Andrew Jackson Elementary Language Academy', 86.0),
 ('Anna R. Langford Community Academy', 31.0),
 ('Annie Keller Elementary Gifted Magnet School', 99.0),
 ('Anthony Overton Elementary School', 32.0),
 ('Ariel Elementary Community Academy', None),
 ('Arna Wendell Bontemps Elementary School', 33.0),
 ('Arnold Mireles Elementary Academy', 27.0),
 ('Arthur A Libby Elementary School', 36.0),
 ('Arthur Dixon Elementary School', 47.0),
 ('Arthur E Canty Elementary School', 87.0),
 ('Arthur R Ashe Elementary School', None),
 ('Asa Philip Randolph Elementary School', 15.0),
 ('Ashburn Community Elementary School', 48.0),
 ('Augustus H Burley Elementary School', 99.0),
 ('Austin Business and Entrepreneurship Academy High School', 38.0),
 ('Austin O Sexton Elementary School', 23.0),
 ('Austin Polytechnical Academy High School', 38.0),
 ('Avalon Park Elementary School', 32.0),
 ('Barbara Vick Early Childhood & Family Center', None),
 ('Belmont-Cragin Elementary School', 75.0),
 ('Benito Juarez Community Academy High School', 46.0),
 ('Benjamin Banneker Elementary School', 36.0),
 ('Benjamin E Mays Elementary Academy', 27.0),
 ('Bernhard Moos Elementary School', 50.0),
 ('Betsy Ross Elementary School', 39.0),
 ('Beulah Shoesmith Elementary School', 45.0),
 ('Blair Early Childhood Center', None),
 ('Bret Harte Elementary School', 63.0),
 ('Brian Piccolo Elementary Specialty School', 27.0),
 ('Brighton Park Elementary School', 55.0),
 ('Bronzeville Scholastic Academy High School', 41.0),
 ('Burnham Elementary Inclusive Academy', 61.0),
 ('Burnside Elementary Scholastic Academy', 51.0),
 ('Calmeca Academy of Fine Arts and Dual Language', 58.0),
 ('Carl Schurz High School', 48.0),
 ('Carl von Linne Elementary School', 68.0),
 ('Carrie Jacobs Bond Elementary School', 54.0),
 ('Carroll-Rosenwald Specialty Elementary School', 35.0),
 ('Carter G Woodson South Elementary School', 26.0),
 ('Cesar E Chavez Multicultural Academic Center Elementary School', 54.0),
 ('Charles Allen Prosser Career Academy High School', 59.0),
 ('Charles Evans Hughes Elementary School', 42.0),
 ('Charles G Hammond Elementary School', 40.0),
 ('Charles Gates Dawes Elementary School', 44.0),
 ('Charles H Wacker Elementary School', 32.0),
 ('Charles Kozminski Elementary Community Academy', 36.0),
 ('Charles N Holden Elementary School', 53.0),
 ('Charles P Caldwell Academy of Math & Science Elementary School', 25.0),
 ('Charles P Steinmetz Academic Centre High School', 26.0),
 ('Charles R Darwin Elementary School', 58.0),
 ('Charles R Henderson Elementary School', 16.0),
 ('Charles S Brownell Elementary School', 20.0),
 ('Charles S Deneen Elementary School', 55.0),
 ('Charles Sumner  Math & Science Community Acad Elementary School', 41.0),
 ('Charles W Earle Elementary School', 24.0),
 ('Chicago Academy Elementary School', 66.0),
 ('Chicago Academy High School', 58.0),
 ('Chicago High School for Agricultural Sciences', 87.0),
 ('Chicago Military Academy High School', 32.0),
 ('Chicago Vocational Career Academy High School', 27.0),
 ('Christian Ebinger Elementary School', 78.0),
 ('Christian Fenger Academy High School', 36.0),
 ('Christopher Columbus Elementary School', 66.0),
 ('Clara Barton Elementary School', 25.0),
 ('Claremont Academy Elementary School', 36.0),
 ('Collins Academy High School', 60.0),
 ('Columbia Explorers Elementary Academy', 59.0),
 ('Countee Cullen Elementary School', 14.0),
 ('Crispus Attucks Elementary School', 45.0),
 ('Crown Community Academy of Fine Arts Center Elementary School', 27.0),
 ('Cyrus H McCormick Elementary School', None),
 ('Daniel Boone Elementary School', 52.0),
 ('Daniel C Beard Elementary School', None),
 ('Daniel Hale Williams Prep School of Medicine', 50.0),
 ('Daniel J Corkery Elementary School', 39.0),
 ('Daniel R Cameron Elementary School', 42.0),
 ('Daniel S Wentworth Elementary School', 30.0),
 ('Daniel Webster Elementary School', 48.0),
 ('David G Farragut Career Academy High School', 43.0),
 ('DeVry University Advantage Academy High School', None),
 ('DeWitt Clinton Elementary School', 47.0),
 ('Dewey Elementary Academy of Fine Arts', 41.0),
 ('Disney II Magnet School', None),
 ('Donald Morrill Math & Science Elementary School', 28.0),
 ('Douglas Taylor Elementary School', 34.0),
 ('Dr  Martin Luther King  Jr  College Prep High School', None),
 ('Dr Jorge Prieto Math and Science', None),
 ('Dumas Technology Academy', 19.0),
 ('Dunne Technology Academy', 46.0),
 ('Durkin Park Elementary School', 61.0),
 ('Dvorak Technology Academy', 46.0),
 ('Dyett High School', 27.0),
 ('Edgar Allan Poe Elementary Classical School', 99.0),
 ('Edgebrook Elementary School', 99.0),
 ('Edison Park Elementary School', 95.0),
 ('Edmond Burke Elementary School', 1.0),
 ('Edward A Bouchet Math & Science Academy Elementary School', 33.0),
 ('Edward Beasley Elementary Magnet Academic Center', 47.0),
 ('Edward C Delano Elementary School', 38.0),
 ('Edward Coles Elementary Language Academy', 22.0),
 ('Edward Everett Elementary School', None),
 ('Edward Jenner Elementary Academy of the Arts', 50.0),
 ('Edward K Ellington Elementary School', 30.0),
 ('Edward N Hurley Elementary School', 77.0),
 ('Edward Tilden Career Community Academy High School', 34.0),
 ('Edward White Elementary Career Academy', 27.0),
 ('Edwin G Foreman High School', 26.0),
 ('Elaine O Goodlow Elementary Magnet School', 44.0),
 ('Eli Whitney Elementary School', 44.0),
 ('Elihu Yale Elementary School', 29.0),
 ('Eliza Chappell Elementary School', 70.0),
 ('Elizabeth H Sutherland Elementary School', 86.0),
 ('Elizabeth Peabody Elementary School', 51.0),
 ('Ella Flagg Young Elementary School', 31.0),
 ('Ellen H Richards Career Academy High School', 30.0),
 ('Ellen Mitchell Elementary School', 99.0),
 ('Emil G Hirsch Metropolitan High School', 13.0),
 ('Emiliano Zapata Elementary Academy', 60.0),
 ('Emmett Louis Till Math and Science Academy', 31.0),
 ('Enrico Fermi Elementary School', 30.0),
 ('Enrico Tonti Elementary School', None),
 ('Eric Solorio Academy High School', 67.0),
 ('Ernst Prussing Elementary School', 71.0),
 ('Esmond Elementary School', 36.0),
 ('Eugene Field Elementary School', 42.0),
 ('Everett McKinley Dirksen Elementary School', 44.0),
 ('Evergreen Academy Middle School', 60.0),
 ('Fairfield Elementary Academy', 31.0),
 ('Federico Garcia Lorca Elementary School', 53.0),
 ('Ferdinand Peck Elementary School', 51.0),
 ('Fernwood Elementary School', 29.0),
 ('Florence B Price Elementary School', 20.0),
 ('Florence Nightingale Elementary School', 35.0),
 ('Fort Dearborn Elementary School', 34.0),
 ('Foster Park Elementary School', 11.0),
 ('Francis M McKay Elementary School', 23.0),
 ('Francis Parkman Elementary School', 38.0),
 ('Francis Scott Key Elementary School', 37.0),
 ('Francis W Parker Elementary Community Academy', 30.0),
 ('Francisco I Madero Middle School', 49.0),
 ('Frank I Bennett Elementary School', 46.0),
 ('Frank L Gillespie Elementary School', 27.0),
 ('Frank W Gunsaulus Elementary Scholastic Academy', 46.0),
 ('Frank W Reilly Elementary School', 48.0),
 ('Franklin Elementary Fine Arts Center', 87.0),
 ('Franz Peter Schubert Elementary School', None),
 ('Frazier Prospective IB Magnet Elementary School', 60.0),
 ('Frederic Chopin Elementary School', 86.0),
 ('Frederick A Douglass Academy High School', 44.0),
 ('Frederick Funston Elementary School', 16.0),
 ('Frederick Stock Elementary School', None),
 ('Friedrich Ludwig Jahn Elementary School', 72.0),
 ('Friedrich W von Steuben Metropolitan Science High School', 70.0),
 ('Gage Park High School', 14.0),
 ('Galileo Math & Science Scholastic Academy Elementary School', 65.0),
 ('Garrett A Morgan Elementary School', 28.0),
 ('Genevieve Melody Elementary School', 61.0),
 ('George Armstrong International Studies Elementary School', 59.0),
 ('George B McClellan Elementary School', 49.0),
 ('George B Swift Elementary Specialty School', 61.0),
 ('George F Cassell Elementary School', 76.0),
 ('George H Corliss High School', 33.0),
 ('George Leland Elementary School', None),
 ('George M Pullman Elementary School', 59.0),
 ('George Manierre Elementary School', 43.0),
 ('George Rogers Clark Elementary School', 39.0),
 ('George W Curtis Elementary School', 23.0),
 ('George W Tilton Elementary School', 6.0),
 ('George Washington Carver Military Academy High School', 53.0),
 ('George Washington Carver Primary School', 25.0),
 ('George Washington Elementary School', 58.0),
 ('George Washington High School', 46.0),
 ('George Westinghouse High School', 74.0),
 ('Gerald Delgado Kanoon Elementary Magnet School', 44.0),
 ('Graeme Stewart Elementary School', 49.0),
 ('Granville T Woods Math & Science Academy Elementary School', 35.0),
 ('Greater Lawndale High School For Social Justice', 43.0),
 ('Grover Cleveland Elementary School', 64.0),
 ('Guglielmo Marconi Elementary Community Academy', 26.0),
 ('Gurdon S Hubbard High School', 42.0),
 ('Gwendolyn Brooks College Preparatory Academy High School', 64.0),
 ('Hannah G Solomon Elementary School', 78.0),
 ('Hanson Park Elementary School', 35.0),
 ('Harold Washington Elementary School', 28.0),
 ('Harriet Beecher Stowe Elementary School', 28.0),
 ('Harriet E Sayre Elementary Language Academy', 68.0),
 ('Hawthorne Elementary Scholastic Academy', 92.0),
 ('Helen M Hefferan Elementary School', 29.0),
 ('Helen Peirce International Studies Elementary School', 58.0),
 ('Helge A Haugan Elementary School', 43.0),
 ('Henry Clay Elementary School', 38.0),
 ('Henry D Lloyd Elementary School', None),
 ('Henry H Nash Elementary School', 41.0),
 ('Henry O Tanner Elementary School', 33.0),
 ('Henry R Clissold Elementary School', 45.0),
 ('High School of Leadership at South Shore', None),
 ('Hiram H Belding Elementary School', 64.0),
 ('Hope College Preparatory High School', 31.0),
 ('Horace Greeley Elementary School', 65.0),
 ('Horace Mann Elementary School', 28.0),
 ('Horatio May Elementary Community Academy', 42.0),
 ('Hyde Park Academy High School', 29.0),
 ('Hyman G Rickover Naval Academy High School', 64.0),
 ('Ida B Wells Preparatory Elementary Academy', 49.0),
 ('Ignance Paderewski Elementary Learning Academy', 31.0),
 ('Infinity Math Science and Technology High School', 58.0),
 ('Inter-American Elementary Magnet School', 67.0),
 ('Ira F Aldridge Elementary School', 39.0),
 ('Irene C. Hernandez Middle School for the Advancement of Science', 34.0),
 ('Irma C Ruiz Elementary School', 57.0),
 ('Irvin C Mollison Elementary School', 44.0),
 ("Isabelle C O'Keeffe Elementary School", 17.0),
 ('Jackie Robinson Elementary School', None),
 ('Jacob Beidler Elementary School', 63.0),
 ('Jacqueline B Vaughn Occupational High School', 57.0),
 ('James B Farnsworth Elementary School', 55.0),
 ('James B McPherson Elementary School', 71.0),
 ('James E McDade Elementary Classical School', 99.0),
 ('James G Blaine Elementary School', 99.0),
 ('James Hedges Elementary School', 22.0),
 ('James Madison Elementary School', 39.0),
 ('James Monroe Elementary School', 45.0),
 ('James N Thorp Elementary School', 32.0),
 ('James Otis Elementary School', 83.0),
 ('James R Doolittle Jr Elementary School', 30.0),
 ('James Russell Lowell Elementary School', 39.0),
 ('James Shields Elementary School', 38.0),
 ('James Wadsworth Elementary School', None),
 ('James Ward Elementary School', 49.0),
 ('James Weldon Johnson Elementary School', 67.0),
 ('Jane A Neil Elementary School', 42.0),
 ('Jane Addams Elementary School', 56.0),
 ('Jean Baptiste Beaubien Elementary School', 63.0),
 ('Jean D Lafayette Elementary School', 44.0),
 ('Jensen Elementary Scholastic Academy', 35.0),
 ('Jesse Owens Elementary Community Academy', None),
 ('Jesse Sherwood Elementary School', 38.0),
 ('Johann W von Goethe Elementary School', 75.0),
 ('John A Walsh Elementary School', 60.0),
 ('John B Drake Elementary School', 59.0),
 ('John B Murphy Elementary School', 80.0),
 ('John Barry Elementary School', 35.0),
 ('John C Burroughs Elementary School', 50.0),
 ('John C Coonley Elementary School', 87.0),
 ('John C Dore Elementary School', 74.0),
 ('John Calhoun North Elementary School', 52.0),
 ('John Charles Haines Elementary School', 32.0),
 ('John D Shoop Math-Science Technical Academy Elementary School', 32.0),
 ('John F Eberhart Elementary School', 42.0),
 ('John F Kennedy High School', 53.0),
 ('John Fiske Elementary School', 13.0),
 ('John Foster Dulles Elementary School', 42.0),
 ('John Greenleaf Whittier Elementary School', 65.0),
 ('John H Hamline Elementary School', 33.0),
 ('John H Kinzie Elementary School', 64.0),
 ('John H Vanderpoel Elementary Magnet School', 74.0),
 ('John Hancock College Preparatory High School', 51.0),
 ('John Harvard Elementary School of Excellence', 51.0),
 ('John Hay Elementary Community Academy', 44.0),
 ('John J Audubon Elementary School', 95.0),
 ('John J Pershing Elementary Humanities Magnet', None),
 ('John L Marsh Elementary School', 72.0),
 ('John M Harlan Community Academy High School', None),
 ('John M Smyth Elementary School', 37.0),
 ('John Marshall Metropolitan High School', 51.0),
 ('John Milton Gregory Elementary School', 44.0),
 ('John P Altgeld Elementary School', 48.0),
 ('John Palmer Elementary School', 75.0),
 ('John Spry Elementary Community School', 66.0),
 ('John T McCutcheon Elementary School', 56.0),
 ('John T Pirie Fine Arts & Academic Center Elementary School', 26.0),
 ('John W Cook Elementary School', None),
 ('John W Garvy Elementary School', 60.0),
 ('John Whistler Elementary School', 45.0),
 ('Johnnie Colemon Elementary Academy', 60.0),
 ('Jonathan Burr Elementary School', 71.0),
 ('Jonathan Y Scammon Elementary School', 44.0),
 ('Jordan Elementary Community School', 61.0),
 ('Jose De Diego Elementary Community Academy', 57.0),
 ('Josefa Ortiz De Dominguez Elementary School', None),
 ('Joseph Brennemann Elementary School', 50.0),
 ('Joseph E Gary Elementary School', 32.0),
 ('Joseph Jungman Elementary School', 36.0),
 ('Joseph Kellman Corporate Community Elementary School', 58.0),
 ('Joseph Lovett Elementary School', 43.0),
 ('Joseph Stockton Elementary School', 37.0),
 ('Joseph Warren Elementary School', 33.0),
 ('Josephine C Locke Elementary School', 57.0),
 ('Joshua D Kershaw Elementary School', 62.0),
 ('Josiah Pickard Elementary School', 50.0),
 ('Joyce Kilmer Elementary School', None),
 ('Julia C Lathrop Elementary School', 67.0),
 ('Julia Ward Howe Elementary School of Excellence', 67.0),
 ('Kate S Buckingham Special Education Center', 31.0),
 ('Kate S Kellogg Elementary School', 76.0),
 ('Kelvyn Park High School', 32.0),
 ('Kenwood Academy High School', 63.0),
 ('LaSalle Elementary Language Academy', 99.0),
 ('LaSalle II Magnet Elementary School', 66.0),
 ('Lake View High School', 64.0),
 ('Langston Hughes Elementary School', 28.0),
 ('Laughlin Falconer Elementary School', 54.0),
 ('Laura S Ward Elementary School', None),
 ('Lawndale Elementary Community Academy', None),
 ('Lazaro Cardenas Elementary School', None),
 ('Leif Ericson Elementary Scholastic Academy', 33.0),
 ('Lenart Elementary Regional Gifted Center', 79.0),
 ('Leslie Lewis Elementary School', 21.0),
 ('Lincoln Park High School', 65.0),
 ('Lionel Hampton Fine & Performing Arts Elementary School', 42.0),
 ('Little Village Elementary School', 45.0),
 ('Logandale Middle School', 56.0),
 ('Lorenz Brentano Math & Science Academy Elementary School', 57.0),
 ('Louis A Agassiz Elementary School', 53.0),
 ('Louis Armstrong Math & Science Elementary School', 42.0),
 ('Louis Nettelhorst Elementary School', 58.0),
 ('Louis Pasteur Elementary School', 50.0),
 ('Louisa May Alcott Elementary School', None),
 ('Ludwig Van Beethoven Elementary School', 40.0),
 ("Luke O'Toole Elementary School", 5.0),
 ('Luther Burbank Elementary School', 37.0),
 ('Lyman A Budlong Elementary School', 59.0),
 ('Lyman Trumbull Elementary School', 56.0),
 ('Mahalia Jackson Elementary School', 38.0),
 ('Mancel Talcott Elementary School', 63.0),
 ('Manley Career Academy High School', 41.0),
 ('Manuel Perez Elementary School', 45.0),
 ('Marcus Moziah Garvey Elementary School', 50.0),
 ('Maria Saucedo Elementary Scholastic Academy', 60.0),
 ('Mariano Azuela Elementary School', 54.0),
 ('Marie Sklodowska Curie Metropolitan High School', 43.0),
 ('Marine Military Math and Science Academy', 41.0),
 ('Mark Sheridan Elementary Math & Science Academy', 74.0),
 ('Mark Skinner Elementary School', 87.0),
 ('Mark Twain Elementary School', 67.0),
 ('Marquette Elementary School', 15.0),
 ('Martha Ruggles Elementary School', 43.0),
 ('Martin A Ryerson Elementary School', 40.0),
 ('Marvin Camras Elementary School', 54.0),
 ('Mary E Courtenay Elementary Language Arts Center', 99.0),
 ('Mary E McDowell Elementary School', None),
 ('Mary Gage Peterson Elementary School', 62.0),
 ('Mary Lyon Elementary School', 55.0),
 ('Mary Mapes Dodge Elementary Renaissance Academy', 57.0),
 ('Mary McLeod Bethune Elementary School', 53.0),
 ('Mason High School', 50.0),
 ('Matthew A Henson Elementary School', 37.0),
 ('Matthew Gallistel Elementary Language Academy', 49.0),
 ('Medgar Evers Elementary School', 27.0),
 ('Melville W Fuller Elementary School', 22.0),
 ('Michael Faraday Elementary School', 35.0),
 ('Michael M Byrne Elementary School', 63.0),
 ('Michele Clark Academic Prep Magnet High School', None),
 ('Mildred I Lavizzo Elementary School', 15.0),
 ('Milton Brunson Math & Science Specialty Elementary School', 30.0),
 ('Minnie Mars Jamieson Elementary School', 64.0),
 ('Miriam G Canter Middle School', 57.0),
 ('Morgan Park High School', 40.0),
 ('Morton School of Excellence', 53.0),
 ('Moses Montefiore Special Elementary School', 28.0),
 ('Mount Greenwood Elementary School', 84.0),
 ('Mount Vernon Elementary School', 31.0),
 ('Multicultural Academy of Scholarship', 48.0),
 ('Myra Bradwell Communications Arts & Sciences Elementary School', 31.0),
 ('Nathan Hale Elementary School', 55.0),
 ('Nathan R Goldblatt Elementary School', 49.0),
 ('Nathan S Davis Elementary School', 43.0),
 ('Nathanael Greene Elementary School', None),
 ('Nathaniel Pope Elementary School', 48.0),
 ('National Teachers Elementary Academy', 67.0),
 ('Neal F Simeon Career Academy High School', 52.0),
 ('Near North Elementary School', 50.0),
 ('New Field Elementary School', None),
 ('New Millennium High School of Health at Bowen', 17.0),
 ('Newton Bateman Elementary School', 55.0),
 ('Nicholas Senn High School', 48.0),
 ('Nicholson Technology Academy', 48.0),
 ('Ninos Heroes Elementary Academic Center', 36.0),
 ('Norman A Bridge Elementary School', 67.0),
 ('North River Elementary School', 67.0),
 ('North-Grand High School', 42.0),
 ('Northside College Preparatory High School', 99.0),
 ('Northside Learning Center High School', 99.0),

# 7. List 5 community areas with highest % of households below poverty line

In [55]:
%%sql
SELECT COMMUNITY_AREA_NAME, PERCENT_HOUSEHOLDS_BELOW_POVERTY
FROM CENSUS_DATA
ORDER BY PERCENT_HOUSEHOLDS_BELOW_POVERTY DESC
LIMIT 5;

 * sqlite:///chinook.db
Done.

[('Riverdale', 56.5),
 ('Fuller Park', 51.2),
 ('Englewood', 46.6),
 ('North Lawndale', 43.1),
 ('East Garfield Park', 42.4)]

# 8. Which community area is most crime prone?

In [57]:
%%sql
SELECT COMMUNITY_AREA_NUMBER, COUNT(*) AS CRIME_COUNT
FROM CHICAGO_CRIME_DATA
GROUP BY COMMUNITY_AREA_NUMBER
ORDER BY CRIME_COUNT DESC
LIMIT 1;

 * sqlite:///chinook.db
Done.

[(25, 43)]

# 9. Use a sub-query to find the name of the community area with highest hardship index

In [59]:
%%sql

SELECT COMMUNITY_AREA_NAME
FROM CENSUS_DATA
WHERE HARDSHIP_INDEX = (SELECT MAX(HARDSHIP_INDEX) FROM CENSUS_DATA);

 * sqlite:///chinook.db
Done.

[('Riverdale',)]

# 10. Use a sub-query to determine the Community Area Name with most number of crimes?

In [76]:
%%sql
SELECT DISTINCT LOCATION_DESCRIPTION
FROM CHICAGO_CRIME_DATA
WHERE LOCATION_DESCRIPTION = (SELECT LOCATION_DESCRIPTION
                       FROM CHICAGO_CRIME_DATA
                       GROUP BY LOCATION_DESCRIPTION
                       ORDER BY COUNT(*) DESC
                       LIMIT 1);

 * sqlite:///chinook.db
Done.

[('STREET',)]